e2e-test

diff --git a/.github/workflows/_e2e_test.yml b/.github/workflows/_e2e_test.yml
--- a/.github/workflows/_e2e_test.yml
+++ b/.github/workflows/_e2e_test.yml
@@ -87,24 +87,25 @@ jobs:
               --no-enable-chunked-prefill \
               --distributed-executor-backend mp \
               --served-model-name Qwen3-VL-30B-A3B-Instruct \
-              --compilation-config '\''{"splitting_ops": ["vllm.unified_attention", "vllm.unified_attention_with_output","vllm.unified_attention_with_output_kunlun","vllm.mamba_mixer2", "vllm.mamba_mixer", "vllm.short_conv", "vllm.linear_attention", "vllm.plamo2_mamba_mixer", "vllm.gdn_attention", "vllm.sparse_attn_indexer"]}'\''
-            
+              --compilation-config '\''{"splitting_ops": ["vllm.unified_attention", "vllm.unified_attention_with_output","vllm.unified_attention_with_output_kunlun","vllm.mamba_mixer2", "vllm.mamba_mixer", "vllm.short_conv", "vllm.linear_attention", "vllm.plamo2_mamba_mixer", "vllm.gdn_attention", "vllm.sparse_attn_indexer"]}'\'''
+      - name: wait for vllm
+        run: |
+          sudo docker exec aiak-hcc-111 bash -lc '
             echo "Waiting for vLLM..."
-            for i in {1..60}; do
-              if curl -sf http://127.0.0.1:8356/v1/models >/dev/null; then
-                echo "vLLM is ready"
-                break
+              for i in {1..60}; do
+                if curl -sf http://127.0.0.1:8356/v1/models >/dev/null; then
+                  echo "vLLM is ready"
+                  break
+                fi
+                sleep 5
+              done
+              if ! curl -sf http://127.0.0.1:8356/v1/models >/dev/null; then
+                echo "vLLM start failed"
+                echo "==== last 200 lines of vllm.log ===="
+                tail -n 200 /workspace/vllm.log || true
+                exit 1
               fi
-              sleep 5
-            done
-            if ! curl -sf http://127.0.0.1:8356/v1/models >/dev/null; then
-              echo "vLLM start failed"
-              echo "==== last 200 lines of vllm.log ===="
-              tail -n 200 /workspace/vllm.log || true
-              exit 1
-            fi
           '
-
 
       # - name: Check xpu and CANN info
       #   run: |
